/*
 * This source file was generated by the Gradle 'init' task
 */
package com.wharvex.gos;

import javax.swing.*;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    SwingUtilities.invokeLater(() -> {
      OSSimulatorGUI.getInstance().setVisible(true);
    });
  }
}
